[ADD] UI Color Env
savoirfairelinux/web-addons pull request #1
Opened 2017-06-05 16:23 UTC by ventilooo

* ui_color_dev
 * ui_color_lab
 * ui_color_help

2017-06-05 20:34 UTC, dufresnedavid commented
@ventilooo The content of views is blue.

![selection_007](https://cloud.githubusercontent.com/assets/8628981/26801761/e411a076-4a0b-11e7-99e8-4bd0b250b833.png)

Also, I oppose to this merge request because I think that those 3 modules are specific to your clients (mainly because the choice of colors is very odd). These modules should not be shared on github.

If we decide to publish modules to change the client theme, I think it needs to be discussed with the whole team (not just developers).

Sorry, but for now, :-1:

2017-06-21 14:39 UTC, joaoalf requested changes
@dufresnedavid Since the need for standard themes per env still exists, I propose that you propose something. We need to porpose something for the team to chose from.

2017-06-21 15:27 UTC, dufresnedavid commented
@joaoalf ok, I will propose something when I get the time. This might take a few months. Otherwise, I am open to suggestions.

2017-12-06 19:56 UTC, ghost approved these changes

2017-12-07 19:55 UTC, ventilooo commented
@joaoalf The categories are fixed

2025-06-17 17:16 UTC, closed without merging