Lmg check allow double booking front end
savoirfairelinux/web-addons pull request #14
Opened 2019-04-01 15:36 UTC by lgharib

Lmg check allow double booking front end

2019-04-01 16:05 UTC, eilst commented on web_calendar_custom/static/src/js/web_calendar_custom.js
> +                                if(typeof stillEvent.record["room_id"][0] != 'undefined' && typeof movingEvent.record["room_id"][0] != 'undefined'){
It's good checking for undefined, but   What if I reserve only an instrument without the room (Possible scenario right? I tried it and there is no room_id on the event.... only intrument) The json dictionary will not have the key "room_id" and there will be an RerefenceError not undefined

2019-05-08 19:41 UTC, rimbendhaou requested changes

2019-05-08 19:41 UTC, rimbendhaou commented on web_calendar_custom/static/src/js/web_calendar_custom.js
> +                        eventOverlap: function(stillEvent, movingEvent) {
These modifications shouldn't be in the web-addons/ web_calendar_custom module

2019-05-08 19:41 UTC, rimbendhaou commented on web_calendar_custom/static/src/js/web_calendar_custom.js
> +                        eventOverlap: function(stillEvent, movingEvent) {
Better to close this PR

2019-05-16 20:00 UTC, closed without merging