[10.0] Add web_float_empty
savoirfairelinux/web-addons pull request #4
Opened 2018-03-09 20:59 UTC by yasmineelmrini

2018-03-27 14:58 UTC, rimbendhaou commented on web_float_empty/__manifest__.py
> +    'category': 'Calendar',
@yasmineelmrini are you sure about the category?

2018-03-27 14:58 UTC, rimbendhaou commented on web_float_empty/__manifest__.py
> +    'name': 'Web Float Empty',
@yasmineelmrini Empty Web Float or Web Float Empty?

2018-03-27 16:33 UTC, rimbendhaou commented on web_float_empty/__manifest__.py
> +    'name': 'Web Float Empty',
@yasmineelmrini Web Float Field Empty

2018-03-29 17:19 UTC, joaoalf requested changes
Just some minor changes.

2018-03-29 17:19 UTC, joaoalf commented on web_float_empty/static/src/js/web_float_empty.js
> +                this.node.attrs.placeholder = '0,00';
@yasmineelmrini Ideally we should use the proper language decimal separator.

2018-03-29 18:43 UTC, joaoalf requested changes
My page was outdated but my point still stands.

2018-03-29 18:43 UTC, joaoalf commented on web_float_empty/static/src/js/web_float_empty.js
> +                this.node.attrs.placeholder = '0,' + '0'.repeat(precision);
@yasmineelmrini I think my point about the decimal separator still stands. Some countries use `,` while others use `.`. Also, what happens if precision == 0?

2018-04-13 16:54 UTC, joaoalf approved these changes
lgtm

2018-04-13 16:59 UTC, rimbendhaou approved these changes

2018-04-13 16:59 UTC, rimbendhaou commented
ok

2018-04-13 17:01 UTC, merged